### ISSUE TITLE
Can't use the search function

### ISSUE THREAD

**Issue by berserkin1337** [burakdrk/searchsen#1]
I can't give input in the search box .  When I hover over the search box the cursor's shape does not change and clicking over the 
search box has no effect either.
**Browser** :  Google Chrome 98.0.4758.102
**Os**: Kubuntu
**Installation Method**: Through the chrome web store

**Comment by burakdrk** [comment]
What is the message inside the search box? Can you provide a screenshot?

**Comment by berserkin1337** [comment]
![searchsen](https://user-images.githubusercontent.com/91308890/156356147-a881b125-86fe-43d7-b6c3-510f2825bd15.png)

**Comment by burakdrk** [comment]
You need to be in a Twitch VOD URL (Something like this: twitch.tv/videos/0123456789) in order to use the extension.
